In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
df = pd.read_csv("Obesity_dataset.csv")
print(df.head())

   Gender   Age  Height  Weight family_history FAVC  FCVC  NCP       CAEC  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0  Sometimes   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0  Sometimes   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0  Sometimes   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0  Sometimes   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0  Sometimes   

  SMOKE  CH2O  SCC  FAF  TUE        CALC                 MTRANS  \
0    no   2.0   no  0.0  1.0          no  Public_Transportation   
1   yes   3.0  yes  3.0  0.0   Sometimes  Public_Transportation   
2    no   2.0   no  2.0  1.0  Frequently  Public_Transportation   
3    no   2.0   no  2.0  0.0  Frequently                Walking   
4    no   2.0   no  0.0  0.0   Sometimes  Public_Transportation   

               Obesity  
0        Normal_Weight  
1        Normal_Weight  
2        Normal_Weight  
3   Overweight_Level_I  
4  Overwe

In [4]:
X = df.drop("Obesity", axis=1)
y = df["Obesity"]


In [5]:
print(df.describe())   # mean, std, min, max for numeric
print(df['Obesity'].value_counts())  # class distribution



               Age       Height       Weight         FCVC          NCP  \
count  2111.000000  2111.000000  2111.000000  2111.000000  2111.000000   
mean     24.312600     1.701677    86.586058     2.419043     2.685628   
std       6.345968     0.093305    26.191172     0.533927     0.778039   
min      14.000000     1.450000    39.000000     1.000000     1.000000   
25%      19.947192     1.630000    65.473343     2.000000     2.658738   
50%      22.777890     1.700499    83.000000     2.385502     3.000000   
75%      26.000000     1.768464   107.430682     3.000000     3.000000   
max      61.000000     1.980000   173.000000     3.000000     4.000000   

              CH2O          FAF          TUE  
count  2111.000000  2111.000000  2111.000000  
mean      2.008011     1.010298     0.657866  
std       0.612953     0.850592     0.608927  
min       1.000000     0.000000     0.000000  
25%       1.584812     0.124505     0.000000  
50%       2.000000     1.000000     0.625350  
75% 

In [6]:
le = LabelEncoder()
df["Obesity"] = le.fit_transform(df["Obesity"])

In [7]:
X = df.drop("Obesity", axis=1)
y = df["Obesity"]


In [8]:
X = pd.get_dummies(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
df["Height"] = df["Height"] * 3.28084
df.rename(columns={"Height": "Height_ft"}, inplace=True)

print(df.head())

   Gender   Age  Height_ft  Weight family_history FAVC  FCVC  NCP       CAEC  \
0  Female  21.0   5.314961    64.0            yes   no   2.0  3.0  Sometimes   
1  Female  21.0   4.986877    56.0            yes   no   3.0  3.0  Sometimes   
2    Male  23.0   5.905512    77.0            yes   no   2.0  3.0  Sometimes   
3    Male  27.0   5.905512    87.0             no   no   3.0  3.0  Sometimes   
4    Male  22.0   5.839895    89.8             no   no   2.0  1.0  Sometimes   

  SMOKE  CH2O  SCC  FAF  TUE        CALC                 MTRANS  Obesity  
0    no   2.0   no  0.0  1.0          no  Public_Transportation        1  
1   yes   3.0  yes  3.0  0.0   Sometimes  Public_Transportation        1  
2    no   2.0   no  2.0  1.0  Frequently  Public_Transportation        1  
3    no   2.0   no  2.0  0.0  Frequently                Walking        5  
4    no   2.0   no  0.0  0.0   Sometimes  Public_Transportation        6  


In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.96      0.96      0.96        56
           1       0.82      0.87      0.84        62
           2       0.99      0.91      0.95        78
           3       0.97      0.98      0.97        58
           4       1.00      1.00      1.00        63
           5       0.86      0.86      0.86        56
           6       0.92      0.94      0.93        50

    accuracy                           0.93       423
   macro avg       0.93      0.93      0.93       423
weighted avg       0.93      0.93      0.93       423

[[54  2  0  0  0  0  0]
 [ 2 54  0  0  0  5  1]
 [ 0  3 71  2  0  0  2]
 [ 0  0  1 57  0  0  0]
 [ 0  0  0  0 63  0  0]
 [ 0  7  0  0  0 48  1]
 [ 0  0  0  0  0  3 47]]


In [13]:
def predict_obesity(input_data):
    input_scaled = scaler.transform([input_data])
    prediction = model.predict(input_scaled)[0]
    return le.inverse_transform([prediction])[0]


In [14]:
# Example: predict for one row from test set
sample = X_test[0]
print("Predicted:", predict_obesity(sample))


Predicted: Normal_Weight


C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [16]:
import pandas as pd

df = pd.read_csv("Obesity_dataset.csv")

# Define thresholds for each numeric column
thresholds = {
    "FCVC": 2.5,   # e.g., eats vegetables frequently if > 2.5
    "NCP": 2.5,    # e.g., more than 2 meals/day
    "CH2O": 2.0,   # e.g., drinks > 2 liters water/day
    "FAF": 1.0,    # e.g., does physical activity > 1 time/week
    "TUE": 2.0     # e.g., spends > 2 hours/day on tech devices
}

# Apply conversion
for col, thresh in thresholds.items():
    df[col] = df[col].apply(lambda x: "Yes" if x > thresh else "No")

print(df.head())


   Gender   Age  Height  Weight family_history FAVC FCVC  NCP       CAEC  \
0  Female  21.0    1.62    64.0            yes   no   No  Yes  Sometimes   
1  Female  21.0    1.52    56.0            yes   no  Yes  Yes  Sometimes   
2    Male  23.0    1.80    77.0            yes   no   No  Yes  Sometimes   
3    Male  27.0    1.80    87.0             no   no  Yes  Yes  Sometimes   
4    Male  22.0    1.78    89.8             no   no   No   No  Sometimes   

  SMOKE CH2O  SCC  FAF TUE        CALC                 MTRANS  \
0    no   No   no   No  No          no  Public_Transportation   
1   yes  Yes  yes  Yes  No   Sometimes  Public_Transportation   
2    no   No   no  Yes  No  Frequently  Public_Transportation   
3    no   No   no  Yes  No  Frequently                Walking   
4    no   No   no   No  No   Sometimes  Public_Transportation   

               Obesity  
0        Normal_Weight  
1        Normal_Weight  
2        Normal_Weight  
3   Overweight_Level_I  
4  Overweight_Level_II  


In [17]:
import joblib

joblib.dump(model, "obesity_model.pkl")

['obesity_model.pkl']